### ISSUE TITLE
Unclear how to create release builds suitable for time profiling

### ISSUE THREAD

**Issue by jmitchell** [rustwasm/book#112]
**Where in the docs did you come across this?**

[`time-profiling.md`](https://github.com/rustwasm/book/blame/283c2860056011dde44b240cca7f9adab90d1b05/src/game-of-life/time-profiling.md#L6-L8)

**Describe what about it does not make sense**

`npm run build-release` and `npm run build-debug` are no longer used in the tutorial. Running them results in `missing script` errors.

```
$ npm run build-debug
npm ERR! missing script: build-debug

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jake/.npm/_logs/2018-10-08T18_08_09_418Z-debug.log

$ cat /home/jake/.npm/_logs/2018-10-08T18_08_09_418Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/home/jake/.npm-global/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-debug' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose stack Error: missing script: build-debug
4 verbose stack     at run (/home/jake/.npm-global/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /home/jake/.npm-global/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /home/jake/.npm-global/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /home/jake/.npm-global/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at handleExists (/home/jake/.npm-global/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:20)
4 verbose stack     at fs.stat (/home/jake/.npm-global/lib/node_modules/npm/node_modules/read-package-json/read-json.js:390:33)
4 verbose stack     at /home/jake/.npm-global/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
4 verbose stack     at FSReqWrap.oncomplete (fs.js:155:5)
5 verbose cwd /home/jake/s/1/tutorial/rust/wasm-game-of-life/www
6 verbose Linux 4.15.0-36-generic
7 verbose argv "/usr/bin/node" "/home/jake/.npm-global/bin/npm" "run" "build-debug"
8 verbose node v10.11.0
9 verbose npm  v6.4.1
10 error missing script: build-debug
11 verbose exit [ 1, true ]
```

**Why does it not make sense?**

`hello-world.md` used to refer to these scripts, but were [removed when switching to `wasm-pack`](https://github.com/rustwasm/book/commit/58b17600330ccf77df36d5b573015a0219a7b270#diff-a851d93d3b4a41020c4bd0054ab30858L112).

As this is written, the only mention of `npm run build*` is in `time-profiling.md`:

```
rustwasm-book$ rg "npm run build"
src/game-of-life/time-profiling.md
7:> project template, that means using `npm run build-release` instead of `npm run
```

**How could we improve it?**

Clarify how to make a release build suitable for time profiling, and ensure the method is consistent with the rest of the tutorial.

**Comment by fitzgen** [comment]
Woops, this is left over from an old iteration of the book -- fix incoming!
